name: Test Build
on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/lamideag/buildozer:latest
    steps:
      - name: Hello
        run: echo "Container started successfully"
